### ISSUE TITLE
Authenticated API returns no user although being logged in

### ISSUE THREAD

**Issue by LuigiClaudio** [netlify-labs/react-netlify-identity#44]
Hi, I'm new to this and I've started putting together an app that uses the react-netlify-identity bindings in order to achieve the level of flexibility I wanted for the authentication flow using Netlify Identity.

I've been experiences the following issue:
After a period of inactivity (I guess the one hour the token is valid), and given that remember was left to its default `true`, the user is shown as logged is however when checking the current `context`  by pinging the authenticated API using for example the `authedFetch` method, no `user` object seems to exists. I can only see the `identity` object. 

Am I missing any logic for handling such scenario?

I have the working app at this address https://jotty.netlify.app/ - it's connected to FaunaDB using Apollo client for handling a list of plain todo list. This uses the `context.user.sub` to associate a list of todos to a user and as you can image, with the scanario mentioned above, no data is returned when no sub is found in the context.

If I log out the `user` from `useIdentityContext()`, the user object is correctly returned it would seem.

Anyone can suggest what I should look out for?

**Comment by LuigiClaudio** [comment]
I'm testing this solution at the moment, not sure if there's a way of checking whether the token validity has expired or not other than comparing dates:

```
if (tokenExpires < nowDate) {
            load(getFreshJWT())
                .then((res) => res)
                .catch((err) =>  err);
        }
```

**Comment by markfazzio** [comment]
I also struggled with this. I created an app a few months ago using the same exact stack you are discussing, with Gatsby on top. What I've found is you need to call `setUser()` with that updated token to update the user, but you also need to update the token expiration time, since this does not come back from the `getFreshJWT()` (I think it should, the entire token object should come back @dorelljames )

Here is my code right now where I need to update the user context before I make a serverless function call to open the Stripe checkout modal.

```
const openCheckoutModal = async (
    event: SyntheticEvent<HTMLButtonElement>
  ) => {
    event.preventDefault();

    const myToken = await getFreshJWT();
    const updatedUser = {
      ...user,
      token: {
        ...user.token,
        access_token: myToken
      }
    };
    setUser(updatedUser);

    const response = await fetch('/.netlify/functions/create-checkout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${user.token.access_token}`
      },
      body: priceID
    }).then(res => res.json());

    const stripe = await stripePromise;
    const { error } = await stripe.redirectToCheckout({
      sessionId: response.sessionId
    });
    if (error) {
      console.warn('Error:', error);
    }
  };
```

**Comment by LuigiClaudio** [comment]
@markfazzio I'm not sure about your scenario, sorry for late reply but I wanted to test the solution I posted earlier for a little while.
I'll share what is working for me. I’ve created a react hook that checks for the token and the token validity and returns either a fresh token or logs out the user if the token object is null. In regards with this last check, I’ve come across a scenario in which although the user is logged in, the token object is null. 

Then I can use this in the `layout` or any `Provider`.

I’ve created a gist for what I’ve been testing successfully for about 10 days for https://jotty.netlify.app
Gist:
https://gist.github.com/LuigiClaudio/19e3fe739734845ababe247ce8ad7169.js
